name: Test

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: env
    - name: Check out
      uses: actions/checkout@v3
    - name: Explore dir
      run: |
        lsb_release -a
        df -h
        free -h
        pwd; ls -alh;
