name: Build and Deploy

on:
  push:
    branches: [ "main" , "hotfix/**"]
  workflow_dispatch:
    inputs:
      deploy_type:
        description: Type of deployment
        required: true
        default: standard
        type: choice
        options:
          - standard
          - hotfix

permissions:
  issues: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Explore dir
        run: |
          lsb_release -a
          df -h
          free -h
          pwd; ls -alh;

  determine-deploy-type:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      deploy_type: ${{ steps.set-type.outputs.deploy_type }}
    steps:
      - name: Determine deployment type
        id: set-type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "deploy_type=${{ github.event.inputs.deploy_type }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
            echo "deploy_type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "deploy_type=standard" >> $GITHUB_OUTPUT
          fi
          echo "deploy_type"

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Determine deployment type
        id: set-type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "deploy_type=${{ github.event.inputs.deploy_type }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
            echo "deploy_type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "deploy_type=standard" >> $GITHUB_OUTPUT
          fi
          echo "deploy_type"
      - name: Explore dir
        run: |
          lsb_release -a
          df -h
          free -h
          pwd; ls -alh;

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Explore dir
        run: |
          lsb_release -a
          df -h
          free -h
          pwd; ls -alh;
